image:
  file: .gitpod.Dockerfile

tasks:
  - name: TF setup and First provisioning
    command: |
      make start-localstack
      make setup-tf-backend
      make create-test-secret
      make tf-init
      make tf-apply
      
  - name: Pre-commit install
    command: |
      make pre-commit-install

vscode:
  extensions:
    - hashicorp.terraform