image:
  file: .gitpod.Dockerfile

tasks:
  - name: TF setup and First provisioning
    command: |
      make start-localstack
      make tf-init
      make tf-apply
      
  - name: Setup Development Env
    init: |
      make pre-commit-install
      make tflint-init

vscode:
  extensions:
    - hashicorp.terraform
    - HashiCorp.HCL