repos:
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.2
    hooks:
      - id: tofu_fmt
      - id: tofu_tflint
      - id: tofu_validate
      # - id: tofu_tfsec
      
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks